### ISSUE TITLE
Breaking a block with redstone ontop dupes the redstone

### ISSUE THREAD

**Issue by TheDrOfDoctoring** [SpaceWalkerRS/alternate-current#27] opened 2023-06-24 11:18 UTC
Minecraft Version - 1.19.2
Forge Version - 43.2.14, happens from at least 43.2.8.
Alternate Current verison - 1.6.0

Breaking any block which has redstone on top will cause two redstone to be produced, duping the redstone.

Video below shows the bug happening.

https://www.youtube.com/watch?v=O_S2ibNw1xs&ab_channel=TheDrOfDoctoring

**Comment by TurtleY0da** [comment] 2023-06-25 03:45
Happens with me too

Using Minecraft Fabric 1.20.1
Mod Version 1.6.0

**Comment by SpaceWalkerRS** [comment] 2023-06-25 19:59
Thanks for the report! It looks to be caused by the fix in v1.6. I'll get another update out to fix this as soon as I can, but in the meantime reverting back to v1.5 should resolve the issue.

**Comment by SpaceWalkerRS** [comment] 2023-06-25 20:51
fixed in v1.7.0

**Closed by SpaceWalkerRS** 2023-06-25 20:51 UTC
